### ISSUE TITLE
Página introdução com content como texto

### ISSUE THREAD

**Issue by diegorojas** [brainwp/estudio-elastico-portfolio-theme#2]
@matheusgimenez  - Colocar o content da página que recebe o modelo para ser o conteúdo do trecho destacada na imagem abaixo:

![content-intro](https://cloud.githubusercontent.com/assets/3632627/5266723/adb43c06-7a32-11e4-9449-dfec95e9ca26.png)

**Comment by matheusgimenez** [comment]
Preciso de ajuda com isso.. onde ficam os arquivos desse intro?

**Comment by diegorojas** [comment]
opa, é essa aqui matheus:
https://github.com/brasadesign/estudio-elastico-portfolio-theme/blob/master/page-intro.php

**Comment by matheusgimenez** [comment]
Já resolvi
