### ISSUE TITLE
Mudar posição da navegação entre portfolios e somar texto

### ISSUE THREAD

**Issue by diegorojas** [brainwp/estudio-elastico-portfolio-theme#3]
@matheusgimenez - A navegação entre portfolios que está no topo deve ir para baixo de tudo e receber palavras - "Próximo" e "Anterior"

![setas](https://cloud.githubusercontent.com/assets/3632627/5266762/f81fd822-7a32-11e4-9131-8e898254238a.png)

**Comment by matheusgimenez** [comment]
Testa e vê se é só isso mesmo :)

**Comment by diegorojas** [comment]
Onde eu visualizo? No beta num tem item em portfolio :(

**Comment by matheusgimenez** [comment]
http://wp.codeispoetry.info/elastico/portfolio-temp/stephan-doitschinoff-2/

**Comment by diegorojas** [comment]
Blza! Em essência é isso, mas poderia deixar um pouco mais bonito com a mesma fonte dos titulos e com um espaço entre a seta e a palavra, blza?

**Comment by matheusgimenez** [comment]
Agora acho que tá resolvido! :)

**Comment by diegorojas** [comment]
fino!
